/**
 * Hand-placed campus waypoints promoted from in-app export.
 * Loaded on first run when no waypoints exist in localStorage.
 */

import type { Waypoint } from './mockWaypoints'

export const INITIAL_WAYPOINTS: Waypoint[] = [
  {
    id: "wp_accessibility_b81fbc",
    category: "accessibility",
    label: "",
    x: 288.705,
    z: -568.364,
    buildingId: "building_q",
  },
  {
    id: "wp_accessibility_5bc13c",
    category: "accessibility",
    label: "",
    x: 308.888,
    z: -540.488,
    buildingId: "building_q",
  },
  {
    id: "wp_accessibility_26dd61",
    category: "accessibility",
    label: "",
    x: 195.63,
    z: -579.154,
    buildingId: "building_h",
  },
  {
    id: "wp_accessibility_9e43fa",
    category: "accessibility",
    label: "",
    x: 184.805,
    z: -554.977,
    buildingId: "building_h",
  },
  {
    id: "wp_accessibility_ceefbb",
    category: "accessibility",
    label: "",
    x: 129.333,
    z: -546.568,
    buildingId: "building_h",
  },
  {
    id: "wp_accessibility_791706",
    category: "accessibility",
    label: "",
    x: 106.36,
    z: -512.792,
    buildingId: "building_h",
  },
  {
    id: "wp_accessibility_520f60",
    category: "accessibility",
    label: "",
    x: 121.297,
    z: -505.556,
    buildingId: "building_h",
  },
  {
    id: "wp_accessibility_d3f61f",
    category: "elevator",
    label: "",
    x: 120.641,
    z: -521.176,
    buildingId: "building_h",
  },
  {
    id: "wp_accessibility_1d997e",
    category: "parking",
    label: "Lot 20",
    x: 312.298,
    z: -553.922,
    buildingId: null,
  },
  {
    id: "wp_accessibility_e5f00f",
    category: "parking",
    label: "Lot 21",
    x: 320.469,
    z: -513.951,
    buildingId: null,
  },
  {
    id: "wp_accessibility_c3a9bc",
    category: "parking",
    label: "Lot 9",
    x: 203.274,
    z: -561.987,
    buildingId: null,
  },
  {
    id: "wp_accessibility_7390d4",
    category: "parking",
    label: "Lot 11",
    x: 228.813,
    z: -481.83,
    buildingId: null,
  },
  {
    id: "wp_accessibility_7ea005",
    category: "parking",
    label: "Lot 9F",
    x: 77.009,
    z: -568.115,
    buildingId: null,
  },
  {
    id: "wp_accessibility_d3da57",
    category: "accessibility",
    label: "Parking ADA Access",
    x: 12.502,
    z: -461.787,
    buildingId: null,
  },
  {
    id: "wp_accessibility_4bf9fc",
    category: "accessibility",
    label: "Parking ADA Access",
    x: -84.86,
    z: -441.224,
    buildingId: null,
  },
  {
    id: "wp_accessibility_59836e",
    category: "accessibility",
    label: "Parking ADA Access",
    x: 13.613,
    z: -424.058,
    buildingId: null,
  },
  {
    id: "wp_accessibility_0393bb",
    category: "accessibility",
    label: "Parking ADA Access",
    x: -34.489,
    z: -413.401,
    buildingId: null,
  },
  {
    id: "wp_accessibility_2e3d67",
    category: "accessibility",
    label: "",
    x: -82.395,
    z: -408.099,
    buildingId: "building_k",
  },
  {
    id: "wp_accessibility_3afd2b",
    category: "accessibility",
    label: "",
    x: -86.415,
    z: -351.809,
    buildingId: "building_k",
  },
  {
    id: "wp_accessibility_775ee3",
    category: "accessibility",
    label: "",
    x: -86.281,
    z: -338.088,
    buildingId: "building_m",
  },
  {
    id: "wp_accessibility_a99312",
    category: "parking",
    label: "Lot 16",
    x: 30.679,
    z: -464.904,
    buildingId: null,
  },
  {
    id: "wp_accessibility_ca605d",
    category: "parking",
    label: "Lot 18",
    x: -38.447,
    z: -451.667,
    buildingId: null,
  },
  {
    id: "wp_accessibility_365852",
    category: "parking",
    label: "Lot 19",
    x: -49.252,
    z: -425.78,
    buildingId: null,
  },
  {
    id: "wp_accessibility_854add",
    category: "parking",
    label: "Lot 17",
    x: 33.871,
    z: -425.458,
    buildingId: null,
  },
  {
    id: "wp_accessibility_0199fe",
    category: "parking",
    label: "Lot D2",
    x: -73.398,
    z: -332.321,
    buildingId: null,
  },
  {
    id: "wp_accessibility_8c9af7",
    category: "accessibility",
    label: "",
    x: -1.808,
    z: -384.503,
    buildingId: "building_g",
  },
  {
    id: "wp_accessibility_7e7173",
    category: "accessibility",
    label: "",
    x: -3.458,
    z: -342.23,
    buildingId: "building_g",
  },
  {
    id: "wp_accessibility_50f112",
    category: "restroomAllGender",
    label: "",
    x: -32.146,
    z: -374.791,
    buildingId: "building_g",
  },
  {
    id: "wp_parking_4caff5",
    category: "parking",
    label: "Lot C12",
    x: -113.066,
    z: -301.952,
    buildingId: null,
  },
  {
    id: "wp_parking_111b87",
    category: "parking",
    label: "Lot C10",
    x: -112.48,
    z: -246.399,
    buildingId: null,
  },
  {
    id: "wp_parking_3bac5b",
    category: "parking",
    label: "Lot D1",
    x: -83.149,
    z: -245.909,
    buildingId: null,
  },
  {
    id: "wp_parking_c4d0f4",
    category: "parking",
    label: "Lot C8",
    x: -108.847,
    z: -199.862,
    buildingId: null,
  },
  {
    id: "wp_restroomAllGender_62e2c0",
    category: "restroomAllGender",
    label: "",
    x: -51.22,
    z: -304.536,
    buildingId: "building_r",
  },
  {
    id: "wp_elevator_205d29",
    category: "elevator",
    label: "",
    x: -51.837,
    z: -295.805,
    buildingId: "building_g",
  },
  {
    id: "wp_restroomPublic_4e244f",
    category: "restroomPublic",
    label: "",
    x: -34.201,
    z: -287.247,
    buildingId: "building_g",
  },
  {
    id: "wp_accessibility_665934",
    category: "accessibility",
    label: "ADA Access",
    x: -37.093,
    z: -270.635,
    buildingId: "building_r",
  },
  {
    id: "wp_accessibility_963707",
    category: "accessibility",
    label: "",
    x: -10.302,
    z: -275.53,
    buildingId: "building_r",
  },
  {
    id: "wp_accessibility_414df6",
    category: "accessibility",
    label: "",
    x: -63.714,
    z: -276.602,
    buildingId: "building_r",
  },
  {
    id: "wp_accessibility_6c878c",
    category: "accessibility",
    label: "Accessibility",
    x: -64.948,
    z: -263.566,
    buildingId: "building_r",
  },
  {
    id: "wp_accessibility_4cfe83",
    category: "accessibility",
    label: "",
    x: 6.648,
    z: -243.449,
    buildingId: "building_l",
  },
  {
    id: "wp_elevator_7fc2d4",
    category: "elevator",
    label: "Elevator",
    x: 28.302,
    z: -254.867,
    buildingId: "building_l",
  },
  {
    id: "wp_elevator_88661e",
    category: "elevator",
    label: "Elevator",
    x: 105.129,
    z: -246.352,
    buildingId: "building_garage",
  },
  {
    id: "wp_elevator_847e76",
    category: "elevator",
    label: "",
    x: 105.327,
    z: -237.688,
    buildingId: "building_garage",
  },
  {
    id: "wp_accessibility_6ae0b1",
    category: "accessibility",
    label: "",
    x: 105.975,
    z: -227.892,
    buildingId: "building_garage",
  },
  {
    id: "wp_accessibility_56b005",
    category: "accessibility",
    label: "Parking ADA Access",
    x: 232.244,
    z: -236.687,
    buildingId: null,
  },
  {
    id: "wp_parking_083835",
    category: "parking",
    label: "Lot F2",
    x: 232.636,
    z: -228.459,
    buildingId: null,
  },
  {
    id: "wp_parking_33165a",
    category: "parking",
    label: "Lot 7",
    x: 289.452,
    z: -166.334,
    buildingId: null,
  },
  {
    id: "wp_parking_9215a3",
    category: "parking",
    label: "Lot 1B",
    x: 402.14,
    z: -153.623,
    buildingId: null,
  },
  {
    id: "wp_parking_2e77b7",
    category: "parking",
    label: "Lot 1A",
    x: 373.438,
    z: -46.207,
    buildingId: null,
  },
  {
    id: "wp_parking_c00508",
    category: "parking",
    label: "Lot 3A",
    x: 376.558,
    z: -15.509,
    buildingId: null,
  },
  {
    id: "wp_parking_c73d9d",
    category: "parking",
    label: "Lot 3B",
    x: 377.013,
    z: 22.441,
    buildingId: null,
  },
  {
    id: "wp_parking_5cb1d5",
    category: "parking",
    label: "Lot 5",
    x: 373.784,
    z: 79.441,
    buildingId: null,
  },
  {
    id: "wp_parking_2475e9",
    category: "parking",
    label: "Lot 4",
    x: 254.215,
    z: 4.261,
    buildingId: null,
  },
  {
    id: "wp_parking_124ee3",
    category: "parking",
    label: "Lot 6",
    x: 239.803,
    z: 41.92,
    buildingId: null,
  },
  {
    id: "wp_parking_691e11",
    category: "parking",
    label: "Lot 8",
    x: 219.399,
    z: 73.428,
    buildingId: null,
  },
  {
    id: "wp_parking_0b09c5",
    category: "parking",
    label: "Lot 10",
    x: 185.31,
    z: 92.298,
    buildingId: null,
  },
  {
    id: "wp_parking_d5b76f",
    category: "parking",
    label: "Lot 12",
    x: 137.793,
    z: 104.288,
    buildingId: null,
  },
  {
    id: "wp_accessibility_6b8438",
    category: "accessibility",
    label: "Lot 12 ADA Access",
    x: 79.818,
    z: 60.449,
    buildingId: null,
  },
  {
    id: "wp_accessibility_e9743c",
    category: "accessibility",
    label: "Lot 10 ADA Access",
    x: 93.446,
    z: 27.516,
    buildingId: null,
  },
  {
    id: "wp_accessibility_d94e30",
    category: "accessibility",
    label: "Lot 8 ADA Access",
    x: 112.845,
    z: -5.22,
    buildingId: null,
  },
  {
    id: "wp_accessibility_c13449",
    category: "accessibility",
    label: "Lot 6 ADA Access",
    x: 169.668,
    z: -22.255,
    buildingId: null,
  },
  {
    id: "wp_accessibility_983647",
    category: "accessibility",
    label: "Lot 4 ADA Access",
    x: 227.074,
    z: -13.056,
    buildingId: null,
  },
  {
    id: "wp_accessibility_df5733",
    category: "accessibility",
    label: "Lot 4 ADA Access",
    x: 263.453,
    z: -33.698,
    buildingId: null,
  },
  {
    id: "wp_accessibility_c2615c",
    category: "accessibility",
    label: "",
    x: 190.213,
    z: -67.578,
    buildingId: "building_u",
  },
  {
    id: "wp_restroomPublic_e3300a",
    category: "restroomPublic",
    label: "",
    x: 238.203,
    z: -60.459,
    buildingId: "building_u",
  },
  {
    id: "wp_restroomAllGender_bd0507",
    category: "restroomAllGender",
    label: "",
    x: 231.249,
    z: -68.545,
    buildingId: "building_u",
  },
  {
    id: "wp_elevator_557370",
    category: "elevator",
    label: "",
    x: 231.65,
    z: -50.711,
    buildingId: "building_u",
  },
  {
    id: "wp_elevator_c2f4e7",
    category: "accessibility",
    label: "",
    x: 234.441,
    z: -33.383,
    buildingId: "building_u",
  },
  {
    id: "wp_accessibility_be12aa",
    category: "accessibility",
    label: "",
    x: 146.276,
    z: -184.386,
    buildingId: "building_s",
  },
  {
    id: "wp_accessibility_d66f85",
    category: "accessibility",
    label: "",
    x: 142.15,
    z: -136.199,
    buildingId: "building_s",
  },
  {
    id: "wp_accessibility_1412b7",
    category: "accessibility",
    label: "",
    x: 180.696,
    z: -133.491,
    buildingId: "building_s",
  },
  {
    id: "wp_restroomAllGender_2b02a5",
    category: "restroomAllGender",
    label: "",
    x: 143.314,
    z: -169.264,
    buildingId: "building_s",
  },
  {
    id: "wp_restroomAllGender_e531a5",
    category: "restroomPublic",
    label: "",
    x: 154.668,
    z: -169.153,
    buildingId: "building_s",
  },
  {
    id: "wp_accessibility_b9aef1",
    category: "accessibility",
    label: "",
    x: 77.253,
    z: -178.093,
    buildingId: "building_b",
  },
  {
    id: "wp_accessibility_02d471",
    category: "accessibility",
    label: "",
    x: 22.158,
    z: -161.173,
    buildingId: "building_b",
  },
  {
    id: "wp_accessibility_57d642",
    category: "accessibility",
    label: "",
    x: 44.929,
    z: -121.078,
    buildingId: "building_b",
  },
  {
    id: "wp_accessibility_7210ac",
    category: "accessibility",
    label: "",
    x: 3.079,
    z: -115.654,
    buildingId: "building_b",
  },
  {
    id: "wp_elevator_bf6fa6",
    category: "elevator",
    label: "",
    x: 24.614,
    z: -211.741,
    buildingId: "building_b",
  },
  {
    id: "wp_elevator_835296",
    category: "elevator",
    label: "",
    x: 53.607,
    z: -159.867,
    buildingId: "building_b",
  },
  {
    id: "wp_elevator_80b8ed",
    category: "elevator",
    label: "",
    x: 11.842,
    z: -110.075,
    buildingId: "building_b",
  },
  {
    id: "wp_restroomAllGender_183c67",
    category: "restroomAllGender",
    label: "",
    x: 108.959,
    z: -170.151,
    buildingId: "building_b",
  },
  {
    id: "wp_restroomAllGender_d95d49",
    category: "restroomAllGender",
    label: "",
    x: 12.935,
    z: -181.803,
    buildingId: "building_b",
  },
  {
    id: "wp_restroomAllGender_180963",
    category: "restroomAllGender",
    label: "",
    x: 18.391,
    z: -145.787,
    buildingId: "building_b",
  },
  {
    id: "wp_elevator_b46f29",
    category: "elevator",
    label: "",
    x: -40.736,
    z: -145.323,
    buildingId: "building_c",
  },
  {
    id: "wp_accessibility_91e3dc",
    category: "accessibility",
    label: "",
    x: -21.478,
    z: -143.407,
    buildingId: "building_c",
  },
  {
    id: "wp_accessibility_cc7630",
    category: "accessibility",
    label: "",
    x: -23.223,
    z: -103.646,
    buildingId: "building_c",
  },
  {
    id: "wp_accessibility_070f60",
    category: "accessibility",
    label: "",
    x: -78.092,
    z: -101.476,
    buildingId: "building_d",
  },
  {
    id: "wp_accessibility_e2ce53",
    category: "accessibility",
    label: "",
    x: -55.986,
    z: -100.803,
    buildingId: "building_d",
  },
  {
    id: "wp_restroomAllGender_a8d9c6",
    category: "restroomAllGender",
    label: "",
    x: -32.684,
    z: -90.954,
    buildingId: "building_d",
  },
  {
    id: "wp_restroomAllGender_9495c8",
    category: "restroomAllGender",
    label: "",
    x: -54.871,
    z: 25.972,
    buildingId: "building_d",
  },
  {
    id: "wp_restroomAllGender_3f6e53",
    category: "elevator",
    label: "",
    x: -49.23,
    z: -33.33,
    buildingId: "building_d",
  },
  {
    id: "wp_elevator_c20877",
    category: "elevator",
    label: "",
    x: -32.669,
    z: -6.605,
    buildingId: "building_d",
  },
  {
    id: "wp_restroomPublic_37b00c",
    category: "restroomPublic",
    label: "",
    x: -33.136,
    z: -59.539,
    buildingId: "building_d",
  },
  {
    id: "wp_accessibility_2f3d0a",
    category: "accessibility",
    label: "",
    x: -36.588,
    z: -31.466,
    buildingId: "building_d",
  },
  {
    id: "wp_accessibility_d59eb7",
    category: "accessibility",
    label: "",
    x: 4.183,
    z: -86.747,
    buildingId: "building_a",
  },
  {
    id: "wp_restroomAllGender_a10e2e",
    category: "restroomAllGender",
    label: "",
    x: 17.459,
    z: -87.203,
    buildingId: "building_a",
  },
  {
    id: "wp_restroomAllGender_9696d2",
    category: "restroomPublic",
    label: "",
    x: 26.197,
    z: -47.828,
    buildingId: "building_a",
  },
  {
    id: "wp_restroomAllGender_07c482",
    category: "restroomPublic",
    label: "",
    x: 44.857,
    z: 6.73,
    buildingId: "building_a",
  },
  {
    id: "wp_restroomAllGender_89054a",
    category: "accessibility",
    label: "",
    x: 52.792,
    z: 37.348,
    buildingId: "building_a",
  },
  {
    id: "wp_restroomAllGender_d67f05",
    category: "restroomAllGender",
    label: "",
    x: 61.59,
    z: 37.006,
    buildingId: "building_a",
  },
  {
    id: "wp_restroomAllGender_9e2bd1",
    category: "accessibility",
    label: "",
    x: 33.266,
    z: 7.407,
    buildingId: "building_a",
  },
  {
    id: "wp_accessibility_557a50",
    category: "accessibility",
    label: "",
    x: 32.568,
    z: -24.083,
    buildingId: "building_a",
  },
  {
    id: "wp_accessibility_d9b0d2",
    category: "accessibility",
    label: "Parking ADA Access",
    x: -99.551,
    z: -79.983,
    buildingId: null,
  },
  {
    id: "wp_restroomAllGender_d955dd",
    category: "restroomAllGender",
    label: "",
    x: -6.971,
    z: 54.721,
    buildingId: "building_e",
  },
  {
    id: "wp_restroomAllGender_8a878a",
    category: "restroomAllGender",
    label: "",
    x: 163.598,
    z: -71.086,
    buildingId: "building_t",
  },
  {
    id: "wp_restroomPublic_70a8a4",
    category: "restroomPublic",
    label: "",
    x: 134.435,
    z: -52.43,
    buildingId: "building_t",
  },
  {
    id: "wp_restroomPublic_6218c8",
    category: "accessibility",
    label: "",
    x: 146.599,
    z: -58.736,
    buildingId: "building_t",
  },
  {
    id: "wp_accessibility_227ffd",
    category: "accessibility",
    label: "",
    x: 149.875,
    z: -86.31,
    buildingId: "building_t",
  },
  {
    id: "wp_accessibility_b14e89",
    category: "accessibility",
    label: "",
    x: 108.536,
    z: -67.6,
    buildingId: "building_t",
  },
  {
    id: "wp_parking_e2a374",
    category: "parking",
    label: "Lot 15",
    x: 53.338,
    z: 96.899,
    buildingId: null,
  },
  {
    id: "wp_parking_ceb4bb",
    category: "parking",
    label: "Lot 13",
    x: 47.045,
    z: 141.278,
    buildingId: null,
  },
  {
    id: "wp_parking_c8bc51",
    category: "parking",
    label: "Lot B3",
    x: -96.57,
    z: 146.367,
    buildingId: null,
  },
  {
    id: "wp_parking_c5c6f8",
    category: "parking",
    label: "Lot 14",
    x: -78.294,
    z: 71.234,
    buildingId: null,
  },
  {
    id: "wp_parking_aa1be4",
    category: "parking",
    label: "Lot B2",
    x: 21.175,
    z: 64.545,
    buildingId: null,
  },
  {
    id: "wp_parking_ac744b",
    category: "parking",
    label: "Lot C2",
    x: -113.195,
    z: 43.065,
    buildingId: null,
  },
  {
    id: "wp_parking_86dadc",
    category: "parking",
    label: "Lot C3",
    x: -89.776,
    z: 4.764,
    buildingId: null,
  },
  {
    id: "wp_parking_78af42",
    category: "parking",
    label: "Lot C4",
    x: -117.591,
    z: -43.269,
    buildingId: null,
  },
  {
    id: "wp_parking_4ace5b",
    category: "parking",
    label: "Lot C5",
    x: -105.2,
    z: -74.897,
    buildingId: null,
  },
  {
    id: "wp_parking_32d0b3",
    category: "parking",
    label: "Lot C6",
    x: -118.77,
    z: -105.838,
    buildingId: null,
  },
  {
    id: "wp_parking_ea2b7f",
    category: "parking",
    label: "Lot C1",
    x: -122.849,
    z: -75.906,
    buildingId: null,
  },
  {
    id: "wp_parking_bc4b82",
    category: "parking",
    label: "Lot B1",
    x: -25.375,
    z: 64.481,
    buildingId: null,
  },
  {
    id: "wp_parking_4c4f85",
    category: "parking",
    label: "Lot 10C",
    x: 257.465,
    z: 150.764,
    buildingId: null,
  },
  {
    id: "wp_parking_b07ae6",
    category: "accessibility",
    label: "",
    x: -23.402,
    z: 138.516,
    buildingId: null,
  },
]
