/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/campus_greybox.glb -o src/components/Campus.tsx --types
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF

export function Model(props: JSX.IntrinsicElements['group']) {
  const gltf = useGLTF('/models/campus_greybox.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      {/* Render the root scene from the GLB so all children (buildings) appear. */}
      <primitive object={gltf.scene} />
    </group>
  )
}

useGLTF.preload('/models/campus_greybox.glb')
