/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/campus_greybox.glb -o src/components/Campus.tsx --types 
*/

import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

type GLTFResult = {
  nodes: {
    building_e_1: THREE.Mesh
    building_e_2: THREE.Mesh
    building_d_1: THREE.Mesh
    building_d_2: THREE.Mesh
    building_b_1: THREE.Mesh
    building_b_2: THREE.Mesh
    building_c_1: THREE.Mesh
    building_c_2: THREE.Mesh
    building_a_1: THREE.Mesh
    building_a_2: THREE.Mesh
  }
  materials: {
    wall: THREE.MeshStandardMaterial
    roof: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/campus_greybox.glb') as GLTFResult
  
  // Log successful load for debugging
  useEffect(() => {
    console.log('Campus model loaded successfully', { 
      nodeCount: Object.keys(nodes).length,
      materialCount: Object.keys(materials).length 
    })
  }, [nodes, materials])
  
  return (
    <group {...props} dispose={null}>
      <group position={[8.397, 12.501, 80.848]}>
        <mesh geometry={nodes.building_e_1.geometry} material={materials.wall} />
        <mesh geometry={nodes.building_e_2.geometry} material={materials.roof} />
      </group>
      <group position={[-27.126, 11.003, 14.882]}>
        <mesh geometry={nodes.building_d_1.geometry} material={materials.wall} />
        <mesh geometry={nodes.building_d_2.geometry} material={materials.roof} />
      </group>
      <group position={[49.587, 7.792, -95.487]}>
        <mesh geometry={nodes.building_b_1.geometry} material={materials.wall} />
        <mesh geometry={nodes.building_b_2.geometry} material={materials.roof} />
      </group>
      <group position={[-22.11, 11.986, -108.543]}>
        <mesh geometry={nodes.building_c_1.geometry} material={materials.wall} />
        <mesh geometry={nodes.building_c_2.geometry} material={materials.roof} />
      </group>
      <group position={[42.725, 11.742, 22.162]}>
        <mesh geometry={nodes.building_a_1.geometry} material={materials.wall} />
        <mesh geometry={nodes.building_a_2.geometry} material={materials.roof} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/campus_greybox.glb')
